config/routes.rb
Rails.application.routes.draw do

  resources :scenes
  resources :stories
  
  get 'stories/show'

  get 'scenes/index'

  root 'topside#index'
  
  

end

app/models/frame.rb
class Frame < ActiveRecord::Base
    belongs_to :scene
end

app/models/scene.rb
class Scene < ActiveRecord::Base
    belongs_to :story
    has_many :frames
end

app/models/story.rb
class Story < ActiveRecord::Base
    # name:string description:text
    has_many :scenes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  def index
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def show
    #grab all scenes
    #@scenes = Stories.Scenes.all #maybe this doesn't work because .object only works on one object? I am tryin to grab everything.
    
    #how to grab current story?
    #console.log(self.id)? what? I thought I could do this
    @story = Story.find(params[:id])
    @scenes = @story.scenes
  end
end

app/controllers/topside_controller.rb
class TopsideController < ApplicationController
    def index
        @message = "You are currently viewing top side"
        @stories = Story.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/topside_helper.rb
module TopsideHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper_main">
    <%= yield %>
  </div>


</body>
</html>

app/views/scenes/index.html.haml
%h1 Scenes#index
%p Find me in app/views/scenes/index.html.haml

app/views/stories/show.html.haml
%h1="#{@story.name}"

.wrapper_list
  %ul.list_carded
    -@scenes.each do |scene|
      %li
        %table
          %tr
            %td=scene.id

app/views/topside/index.html.haml
%h1= @message
  
This is a list of story. A story refers to project. Two projects can be related, but two are not a continuous story. 
  
.wrapper_list
  %ul.list_carded 
    -@stories.each do |story|
      %li
        %table
          %tr
            %td=story.name
            %td
              = link_to( 'View', story_path(story))
            %td=story.description

            

        